// Generated by gencpp from file pr2_lfd_utils/WMData.msg
// DO NOT EDIT!


#ifndef PR2_LFD_UTILS_MESSAGE_WMDATA_H
#define PR2_LFD_UTILS_MESSAGE_WMDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <pr2_lfd_utils/WMObject.h>

namespace pr2_lfd_utils
{
template <class ContainerAllocator>
struct WMData_
{
  typedef WMData_<ContainerAllocator> Type;

  WMData_()
    : header()
    , objects()  {
    }
  WMData_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , objects(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::pr2_lfd_utils::WMObject_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::pr2_lfd_utils::WMObject_<ContainerAllocator> >> _objects_type;
  _objects_type objects;





  typedef boost::shared_ptr< ::pr2_lfd_utils::WMData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pr2_lfd_utils::WMData_<ContainerAllocator> const> ConstPtr;

}; // struct WMData_

typedef ::pr2_lfd_utils::WMData_<std::allocator<void> > WMData;

typedef boost::shared_ptr< ::pr2_lfd_utils::WMData > WMDataPtr;
typedef boost::shared_ptr< ::pr2_lfd_utils::WMData const> WMDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pr2_lfd_utils::WMData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pr2_lfd_utils::WMData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pr2_lfd_utils::WMData_<ContainerAllocator1> & lhs, const ::pr2_lfd_utils::WMData_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.objects == rhs.objects;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pr2_lfd_utils::WMData_<ContainerAllocator1> & lhs, const ::pr2_lfd_utils::WMData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pr2_lfd_utils

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pr2_lfd_utils::WMData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pr2_lfd_utils::WMData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pr2_lfd_utils::WMData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pr2_lfd_utils::WMData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pr2_lfd_utils::WMData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pr2_lfd_utils::WMData_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pr2_lfd_utils::WMData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "68dcda98ef9b16735859eaf0e9474409";
  }

  static const char* value(const ::pr2_lfd_utils::WMData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x68dcda98ef9b1673ULL;
  static const uint64_t static_value2 = 0x5859eaf0e9474409ULL;
};

template<class ContainerAllocator>
struct DataType< ::pr2_lfd_utils::WMData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pr2_lfd_utils/WMData";
  }

  static const char* value(const ::pr2_lfd_utils::WMData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pr2_lfd_utils::WMData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"WMObject[] objects\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: pr2_lfd_utils/WMObject\n"
"Header header\n"
"uint32 id\n"
"bool currently_visible\n"
"geometry_msgs/PoseStamped pose\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::pr2_lfd_utils::WMData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pr2_lfd_utils::WMData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.objects);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WMData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pr2_lfd_utils::WMData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pr2_lfd_utils::WMData_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "objects[]" << std::endl;
    for (size_t i = 0; i < v.objects.size(); ++i)
    {
      s << indent << "  objects[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::pr2_lfd_utils::WMObject_<ContainerAllocator> >::stream(s, indent + "    ", v.objects[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PR2_LFD_UTILS_MESSAGE_WMDATA_H
