(cl:defpackage robotics_demo-srv
  (:use )
  (:export
   "OBJECTPOSESERVICE"
   "<OBJECTPOSESERVICE-REQUEST>"
   "OBJECTPOSESERVICE-REQUEST"
   "<OBJECTPOSESERVICE-RESPONSE>"
   "OBJECTPOSESERVICE-RESPONSE"
   "POSITIONSERVICE"
   "<POSITIONSERVICE-REQUEST>"
   "POSITIONSERVICE-REQUEST"
   "<POSITIONSERVICE-RESPONSE>"
   "POSITIONSERVICE-RESPONSE"
  ))

