// Generated by gencpp from file articulation_model_msgs/ActionsMsg.msg
// DO NOT EDIT!


#ifndef ARTICULATION_MODEL_MSGS_MESSAGE_ACTIONSMSG_H
#define ARTICULATION_MODEL_MSGS_MESSAGE_ACTIONSMSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Pose.h>

namespace articulation_model_msgs
{
template <class ContainerAllocator>
struct ActionsMsg_
{
  typedef ActionsMsg_<ContainerAllocator> Type;

  ActionsMsg_()
    : header()
    , actions()  {
    }
  ActionsMsg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , actions(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::geometry_msgs::Pose_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Pose_<ContainerAllocator> >> _actions_type;
  _actions_type actions;





  typedef boost::shared_ptr< ::articulation_model_msgs::ActionsMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::articulation_model_msgs::ActionsMsg_<ContainerAllocator> const> ConstPtr;

}; // struct ActionsMsg_

typedef ::articulation_model_msgs::ActionsMsg_<std::allocator<void> > ActionsMsg;

typedef boost::shared_ptr< ::articulation_model_msgs::ActionsMsg > ActionsMsgPtr;
typedef boost::shared_ptr< ::articulation_model_msgs::ActionsMsg const> ActionsMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::articulation_model_msgs::ActionsMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::articulation_model_msgs::ActionsMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::articulation_model_msgs::ActionsMsg_<ContainerAllocator1> & lhs, const ::articulation_model_msgs::ActionsMsg_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.actions == rhs.actions;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::articulation_model_msgs::ActionsMsg_<ContainerAllocator1> & lhs, const ::articulation_model_msgs::ActionsMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace articulation_model_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::articulation_model_msgs::ActionsMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::articulation_model_msgs::ActionsMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::articulation_model_msgs::ActionsMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::articulation_model_msgs::ActionsMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::articulation_model_msgs::ActionsMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::articulation_model_msgs::ActionsMsg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::articulation_model_msgs::ActionsMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "edfe36b729cee3e9f2d41537b0b17fd2";
  }

  static const char* value(const ::articulation_model_msgs::ActionsMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xedfe36b729cee3e9ULL;
  static const uint64_t static_value2 = 0xf2d41537b0b17fd2ULL;
};

template<class ContainerAllocator>
struct DataType< ::articulation_model_msgs::ActionsMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "articulation_model_msgs/ActionsMsg";
  }

  static const char* value(const ::articulation_model_msgs::ActionsMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::articulation_model_msgs::ActionsMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#goal definition\n"
"std_msgs/Header header                        # frame and timestamp\n"
"\n"
"geometry_msgs/Pose[] actions\n"
"\n"
"#---\n"
"#result definition\n"
"#int32[] sequence\n"
"#---\n"
"#feedback\n"
"#int32[] sequence\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::articulation_model_msgs::ActionsMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::articulation_model_msgs::ActionsMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.actions);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ActionsMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::articulation_model_msgs::ActionsMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::articulation_model_msgs::ActionsMsg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "actions[]" << std::endl;
    for (size_t i = 0; i < v.actions.size(); ++i)
    {
      s << indent << "  actions[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "    ", v.actions[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARTICULATION_MODEL_MSGS_MESSAGE_ACTIONSMSG_H
