// Generated by gencpp from file robotics_demo/ObjectPoseServiceRequest.msg
// DO NOT EDIT!


#ifndef ROBOTICS_DEMO_MESSAGE_OBJECTPOSESERVICEREQUEST_H
#define ROBOTICS_DEMO_MESSAGE_OBJECTPOSESERVICEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robotics_demo
{
template <class ContainerAllocator>
struct ObjectPoseServiceRequest_
{
  typedef ObjectPoseServiceRequest_<ContainerAllocator> Type;

  ObjectPoseServiceRequest_()
    : object_name()  {
    }
  ObjectPoseServiceRequest_(const ContainerAllocator& _alloc)
    : object_name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _object_name_type;
  _object_name_type object_name;





  typedef boost::shared_ptr< ::robotics_demo::ObjectPoseServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotics_demo::ObjectPoseServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectPoseServiceRequest_

typedef ::robotics_demo::ObjectPoseServiceRequest_<std::allocator<void> > ObjectPoseServiceRequest;

typedef boost::shared_ptr< ::robotics_demo::ObjectPoseServiceRequest > ObjectPoseServiceRequestPtr;
typedef boost::shared_ptr< ::robotics_demo::ObjectPoseServiceRequest const> ObjectPoseServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotics_demo::ObjectPoseServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotics_demo::ObjectPoseServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robotics_demo::ObjectPoseServiceRequest_<ContainerAllocator1> & lhs, const ::robotics_demo::ObjectPoseServiceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.object_name == rhs.object_name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robotics_demo::ObjectPoseServiceRequest_<ContainerAllocator1> & lhs, const ::robotics_demo::ObjectPoseServiceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robotics_demo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robotics_demo::ObjectPoseServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotics_demo::ObjectPoseServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotics_demo::ObjectPoseServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotics_demo::ObjectPoseServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotics_demo::ObjectPoseServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotics_demo::ObjectPoseServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotics_demo::ObjectPoseServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2f12226348d323c2e5b2031b3da53f1b";
  }

  static const char* value(const ::robotics_demo::ObjectPoseServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2f12226348d323c2ULL;
  static const uint64_t static_value2 = 0xe5b2031b3da53f1bULL;
};

template<class ContainerAllocator>
struct DataType< ::robotics_demo::ObjectPoseServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotics_demo/ObjectPoseServiceRequest";
  }

  static const char* value(const ::robotics_demo::ObjectPoseServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotics_demo::ObjectPoseServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string object_name\n"
;
  }

  static const char* value(const ::robotics_demo::ObjectPoseServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotics_demo::ObjectPoseServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.object_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectPoseServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotics_demo::ObjectPoseServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotics_demo::ObjectPoseServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "object_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.object_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTICS_DEMO_MESSAGE_OBJECTPOSESERVICEREQUEST_H
