// Generated by gencpp from file robotics_demo/PositionServiceRequest.msg
// DO NOT EDIT!


#ifndef ROBOTICS_DEMO_MESSAGE_POSITIONSERVICEREQUEST_H
#define ROBOTICS_DEMO_MESSAGE_POSITIONSERVICEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <robotics_demo/PosRot.h>

namespace robotics_demo
{
template <class ContainerAllocator>
struct PositionServiceRequest_
{
  typedef PositionServiceRequest_<ContainerAllocator> Type;

  PositionServiceRequest_()
    : input()  {
    }
  PositionServiceRequest_(const ContainerAllocator& _alloc)
    : input(_alloc)  {
  (void)_alloc;
    }



   typedef  ::robotics_demo::PosRot_<ContainerAllocator>  _input_type;
  _input_type input;





  typedef boost::shared_ptr< ::robotics_demo::PositionServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotics_demo::PositionServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PositionServiceRequest_

typedef ::robotics_demo::PositionServiceRequest_<std::allocator<void> > PositionServiceRequest;

typedef boost::shared_ptr< ::robotics_demo::PositionServiceRequest > PositionServiceRequestPtr;
typedef boost::shared_ptr< ::robotics_demo::PositionServiceRequest const> PositionServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotics_demo::PositionServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotics_demo::PositionServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robotics_demo::PositionServiceRequest_<ContainerAllocator1> & lhs, const ::robotics_demo::PositionServiceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.input == rhs.input;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robotics_demo::PositionServiceRequest_<ContainerAllocator1> & lhs, const ::robotics_demo::PositionServiceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robotics_demo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robotics_demo::PositionServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotics_demo::PositionServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotics_demo::PositionServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotics_demo::PositionServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotics_demo::PositionServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotics_demo::PositionServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotics_demo::PositionServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bd0742a57f699ed2087743384a0ea3dd";
  }

  static const char* value(const ::robotics_demo::PositionServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbd0742a57f699ed2ULL;
  static const uint64_t static_value2 = 0x087743384a0ea3ddULL;
};

template<class ContainerAllocator>
struct DataType< ::robotics_demo::PositionServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotics_demo/PositionServiceRequest";
  }

  static const char* value(const ::robotics_demo::PositionServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotics_demo::PositionServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "PosRot input\n"
"\n"
"================================================================================\n"
"MSG: robotics_demo/PosRot\n"
"float32 pos_x\n"
"float32 pos_y\n"
"float32 pos_z\n"
"float32 rot_x\n"
"float32 rot_y\n"
"float32 rot_z\n"
"float32 rot_w\n"
"string id\n"
;
  }

  static const char* value(const ::robotics_demo::PositionServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotics_demo::PositionServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.input);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PositionServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotics_demo::PositionServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotics_demo::PositionServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "input: ";
    s << std::endl;
    Printer< ::robotics_demo::PosRot_<ContainerAllocator> >::stream(s, indent + "  ", v.input);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTICS_DEMO_MESSAGE_POSITIONSERVICEREQUEST_H
