// Generated by gencpp from file robotics_demo/PositionServiceResponse.msg
// DO NOT EDIT!


#ifndef ROBOTICS_DEMO_MESSAGE_POSITIONSERVICERESPONSE_H
#define ROBOTICS_DEMO_MESSAGE_POSITIONSERVICERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <robotics_demo/PosRot.h>

namespace robotics_demo
{
template <class ContainerAllocator>
struct PositionServiceResponse_
{
  typedef PositionServiceResponse_<ContainerAllocator> Type;

  PositionServiceResponse_()
    : output()  {
    }
  PositionServiceResponse_(const ContainerAllocator& _alloc)
    : output(_alloc)  {
  (void)_alloc;
    }



   typedef  ::robotics_demo::PosRot_<ContainerAllocator>  _output_type;
  _output_type output;





  typedef boost::shared_ptr< ::robotics_demo::PositionServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotics_demo::PositionServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PositionServiceResponse_

typedef ::robotics_demo::PositionServiceResponse_<std::allocator<void> > PositionServiceResponse;

typedef boost::shared_ptr< ::robotics_demo::PositionServiceResponse > PositionServiceResponsePtr;
typedef boost::shared_ptr< ::robotics_demo::PositionServiceResponse const> PositionServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotics_demo::PositionServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotics_demo::PositionServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robotics_demo::PositionServiceResponse_<ContainerAllocator1> & lhs, const ::robotics_demo::PositionServiceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.output == rhs.output;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robotics_demo::PositionServiceResponse_<ContainerAllocator1> & lhs, const ::robotics_demo::PositionServiceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robotics_demo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robotics_demo::PositionServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotics_demo::PositionServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotics_demo::PositionServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotics_demo::PositionServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotics_demo::PositionServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotics_demo::PositionServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotics_demo::PositionServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3de20a0b2a7468dbd60e3a558bf7e00d";
  }

  static const char* value(const ::robotics_demo::PositionServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3de20a0b2a7468dbULL;
  static const uint64_t static_value2 = 0xd60e3a558bf7e00dULL;
};

template<class ContainerAllocator>
struct DataType< ::robotics_demo::PositionServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotics_demo/PositionServiceResponse";
  }

  static const char* value(const ::robotics_demo::PositionServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotics_demo::PositionServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "PosRot output\n"
"\n"
"================================================================================\n"
"MSG: robotics_demo/PosRot\n"
"float32 pos_x\n"
"float32 pos_y\n"
"float32 pos_z\n"
"float32 rot_x\n"
"float32 rot_y\n"
"float32 rot_z\n"
"float32 rot_w\n"
"string id\n"
;
  }

  static const char* value(const ::robotics_demo::PositionServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotics_demo::PositionServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.output);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PositionServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotics_demo::PositionServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotics_demo::PositionServiceResponse_<ContainerAllocator>& v)
  {
    s << indent << "output: ";
    s << std::endl;
    Printer< ::robotics_demo::PosRot_<ContainerAllocator> >::stream(s, indent + "  ", v.output);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTICS_DEMO_MESSAGE_POSITIONSERVICERESPONSE_H
